"""
Prompt Lookup Decoding (PLD) for vmlx-engine.

Draft tokens are generated by searching the existing token sequence for
n-gram matches and returning the tokens that follow the match. No draft
model is required — the prompt itself is the draft library.

Phase 1 (this file): measurement infrastructure.
  - find_draft_tokens(): n-gram search, pure Python, zero model calls
  - PromptLookupStats: retrospective acceptance-rate tracking
  - pld_stats: process-global singleton logged every N tokens

Phase 2 (future): actual acceleration via batched verification.
  - The scheduler already holds self.model and can call it directly
    (see _prefill_for_prompt_only_cache for the pattern).
  - Verification: self.model(mx.array([[last_tok, d1, ..., dK]]), cache=...)
    returns K+1 logits in ONE forward pass instead of K sequential passes.
  - KV cache rollback: truncate accepted-prefix KV tensors (same pattern
    as _truncate_cache_to_prompt_length).
  - Blocked today by: BatchGenerator holds KV cache internally; we can't
    extract it mid-stream without upstream mlx-lm changes.

Reference: "A Simple Framework for Prompt Lookup Decoding" (Saxena, 2023)
See also: notes/prompt-lookup-decoding.md
"""

import logging
from dataclasses import dataclass, field
from typing import Dict, List, Tuple

logger = logging.getLogger(__name__)

_LOG_INTERVAL = 200  # log stats every N tokens


def find_draft_tokens(
    token_ids: List[int],
    num_draft_tokens: int = 5,
    max_ngram_size: int = 3,
) -> List[int]:
    """
    Find draft tokens by n-gram matching within the token sequence.

    Searches for the largest n-gram (up to max_ngram_size) whose last
    occurrence in the sequence is earlier than the current position, then
    returns up to num_draft_tokens tokens that follow it.

    Args:
        token_ids:        Full sequence (prompt + output so far).
        num_draft_tokens: Max draft tokens to return.
        max_ngram_size:   Largest n-gram to try (3 is a good default).

    Returns:
        List of draft token IDs, possibly empty.
    """
    n = len(token_ids)
    if n < 3 or num_draft_tokens <= 0:
        return []

    for ngram_size in range(min(max_ngram_size, n - 1), 1, -1):
        query = token_ids[-ngram_size:]
        # Scan backward: most recent prior occurrence gives best acceptance on
        # repetitive/structured output.  Exclude the last position (that is the
        # query itself) so we always look at an *earlier* occurrence.
        for i in range(n - ngram_size - 1, -1, -1):
            if token_ids[i : i + ngram_size] == query:
                draft_start = i + ngram_size
                draft = token_ids[draft_start : draft_start + num_draft_tokens]
                if draft:
                    return list(draft)

    return []


class NgramIndex:
    """O(1) n-gram lookup via hash index, replacing the O(n) backward scan.

    Maintains bigram and trigram dicts mapping n-gram tuples to their two
    most recent positions.  Storing two positions handles the self-match edge
    case: the query's own position may be the most recent entry, so we fall
    back to the second.

    Usage (per-request, in scheduler):
        idx = NgramIndex()
        drafts = idx.find_drafts(full_tokens, num_draft_tokens=2)
    The index is built lazily on the first call and updated incrementally
    on subsequent calls.
    """

    __slots__ = ("_index", "_indexed_up_to")

    def __init__(self) -> None:
        self._index: Dict[Tuple[int, ...], Tuple[int, int]] = {}
        self._indexed_up_to: int = 0

    def _add(self, key: Tuple[int, ...], pos: int) -> None:
        prev = self._index.get(key)
        if prev is None:
            self._index[key] = (pos, -1)
        elif pos > prev[0]:
            self._index[key] = (pos, prev[0])

    def find_drafts(
        self,
        token_ids: List[int],
        num_draft_tokens: int = 5,
        max_ngram_size: int = 3,
    ) -> List[int]:
        n = len(token_ids)
        if n < 3 or num_draft_tokens <= 0:
            return []

        # Incrementally index new positions
        for i in range(self._indexed_up_to, n - 1):
            self._add((token_ids[i], token_ids[i + 1]), i)
            if i + 2 < n:
                self._add((token_ids[i], token_ids[i + 1], token_ids[i + 2]), i)
        self._indexed_up_to = max(self._indexed_up_to, n - 1)

        # Lookup: try largest n-gram first (trigram > bigram)
        for ngram_size in range(min(max_ngram_size, n - 1), 1, -1):
            key = tuple(token_ids[-ngram_size:])
            before = n - ngram_size  # positions at or after this are self-matches
            entry = self._index.get(key)
            if entry is None:
                continue
            pos = entry[0] if entry[0] < before else entry[1]
            if pos < 0:
                continue
            draft_start = pos + ngram_size
            drafts = token_ids[draft_start : draft_start + num_draft_tokens]
            if drafts:
                return list(drafts)

        return []


@dataclass
class PromptLookupStats:
    """
    Retrospective acceptance-rate tracker for prompt lookup decoding.

    For every token the scheduler generates we:
      1. Find draft tokens for the NEXT position and store them.
      2. On subsequent tokens, check whether the actual token matched
         the draft prediction.

    This does NOT affect generation — it only measures what WOULD happen
    if batched verification were implemented.

    Attributes:
        total_tokens:     Total tokens generated (denominator).
        draft_found:      Positions where we found an n-gram match.
        first_hit:        Times the first draft token was correct.
        total_hit_depth:  Sum of consecutive correct predictions across
                          all sequences (numerator for mean depth).
        completed_seqs:   Number of draft sequences that fully resolved
                          (hit all drafts or hit a miss).
    """

    total_tokens: int = 0
    draft_found: int = 0
    first_hit: int = 0
    total_hit_depth: int = 0
    completed_seqs: int = 0

    # -----------------------------------------------------------------
    # Derived metrics

    @property
    def coverage(self) -> float:
        """Fraction of positions where an n-gram match was found."""
        return self.draft_found / max(1, self.total_tokens)

    @property
    def first_token_hit_rate(self) -> float:
        """P(first draft token correct | draft was found)."""
        return self.first_hit / max(1, self.draft_found)

    @property
    def mean_hit_depth(self) -> float:
        """Mean consecutive correct drafts per hit sequence."""
        return self.total_hit_depth / max(1, self.first_hit)

    @property
    def theoretical_speedup(self) -> float:
        """
        Estimated throughput multiplier with perfect batched verification.

        Each hit-depth-D sequence produces D+1 tokens in 1 forward pass
        instead of D+1 sequential passes, saving D passes.
        tokens_saved = total_hit_depth (one saved pass per consecutive hit).
        speedup      = total_tokens / (total_tokens - tokens_saved)
        """
        saved = self.total_hit_depth
        effective_passes = max(1, self.total_tokens - saved)
        return self.total_tokens / effective_passes

    # -----------------------------------------------------------------

    def log_summary(self) -> None:
        if self.total_tokens == 0:
            return
        logger.info(
            "[PLD] tokens=%d  coverage=%.1f%%  hit@1=%.1f%%  "
            "mean_depth=%.2f  theoretical_speedup=%.2fx",
            self.total_tokens,
            self.coverage * 100,
            self.first_token_hit_rate * 100,
            self.mean_hit_depth,
            self.theoretical_speedup,
        )


# Process-global singleton. Reset with pld_stats.__init__() between benchmarks.
pld_stats = PromptLookupStats()
