import { describe, expect, it } from 'vitest'
import { ImageDraftStore } from '../src/shared/imageDrafts'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

describe('renderer-lifetime image draft ownership', () => {
  it('retains all fields across unsubscribe/remount without persisting media to disk', () => {
    const store = new ImageDraftStore()
    store.activate('qwen-q8')
    const unsubscribe = store.subscribe(() => {})
    store.update(store.getSnapshot(), { prompt: 'make it blue', sourceImage: { name: 'a.png', dataUrl: 'data:image/png;base64,A' }, maskBase64: 'mask', iteratePrompt: 'original', iterateCounter: 2 })
    const saved = store.getSnapshot().draft
    unsubscribe()
    store.activate('qwen-q8')
    expect(store.getSnapshot().draft).toEqual(saved)
  })
  it('isolates histories and models and restores the last selected conversation per model', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    store.select('a')
    store.update(store.getSnapshot(), { prompt: 'A' })
    store.select('b')
    expect(store.getSnapshot().draft.prompt).toBe('')
    store.update(store.getSnapshot(), { prompt: 'B' })
    store.activate('schnell')
    expect(store.getSnapshot().draft.prompt).toBe('')
    store.activate('qwen')
    expect(store.getSnapshot().currentSessionId).toBe('b')
    expect(store.getSnapshot().draft.prompt).toBe('B')
    store.select('a')
    expect(store.getSnapshot().draft.prompt).toBe('A')
  })
  it('rejects late picker/Iterate callbacks even after navigating away and back', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    const old = store.getSnapshot()
    store.select('other')
    store.select(null)
    expect(store.update(old, { sourceImage: { name: 'late', dataUrl: 'late' } })).toBe(false)
    expect(store.getSnapshot().draft.sourceImage).toBeNull()
  })
  it('promotes an unsaved draft to its created conversation without losing edits', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    const request = store.getSnapshot()
    store.update(request, { prompt: 'updated during create' })
    store.promote(request, 'created')
    expect(store.getSnapshot().currentSessionId).toBe('created')
    expect(store.getSnapshot().draft.prompt).toBe('updated during create')
    store.newConversation()
    expect(store.getSnapshot().draft.prompt).toBe('')
    store.select('created')
    expect(store.getSnapshot().draft.prompt).toBe('updated during create')
  })
  it('does not navigate back when a previous create finishes late', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    store.update(store.getSnapshot(), { prompt: 'submitted' })
    const request = store.getSnapshot()
    store.newConversation()
    store.update(store.getSnapshot(), { prompt: 'new work' })
    store.promote(request, 'created')
    expect(store.getSnapshot().currentSessionId).toBeNull()
    expect(store.getSnapshot().draft.prompt).toBe('new work')
    store.select('created')
    expect(store.getSnapshot().draft.prompt).toBe('submitted')
  })
  it('deletion clears only that history and invalidates late callbacks', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    store.select('deleted')
    const old = store.getSnapshot()
    store.remove('deleted')
    expect(store.update(old, { prompt: 'resurrect' })).toBe(false)
    store.select('deleted')
    expect(store.getSnapshot().draft.prompt).toBe('')
  })
  it('keeps snapshot stable for React subscriptions until a real change', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    const snapshot = store.getSnapshot()
    store.activate('qwen')
    expect(store.getSnapshot()).toBe(snapshot)
  })
  it('rejecting a folder does not activate another owner or discard the current draft', () => {
    const store = new ImageDraftStore()
    store.activate('qwen')
    store.update(store.getSnapshot(), { prompt: 'keep', maskBase64: 'mask' })
    const snapshot = store.getSnapshot()
    // Main validates before returning success; the renderer must only activate on success.
    const src = readFileSync(join(__dirname, '../src/renderer/src/components/image/ImageTab.tsx'), 'utf8')
    const selection = src.slice(src.indexOf('const handleModelSelect'), src.indexOf('const handleSubmit'))
    const beforeSuccess = selection.slice(0, selection.indexOf('if (result.success)'))
    expect(beforeSuccess).not.toMatch(/imageDrafts\.(activate|update|select|newConversation)|setSourceImage|setMaskBase64/)
    expect(store.getSnapshot()).toBe(snapshot)
  })
  it('wires a controlled prompt without resetting it on composer remount', () => {
    const src = readFileSync(join(__dirname, '../src/renderer/src/components/image/ImagePromptBar.tsx'), 'utf8')
    expect(src).toContain('onPromptChange: setPrompt')
    expect(src).not.toContain("setPrompt('')")
    const tab = readFileSync(join(__dirname, '../src/renderer/src/components/image/ImageTab.tsx'), 'utf8')
    expect(tab).toContain('prompt={prompt}')
    expect(tab).toContain('onPromptChange={setPrompt}')
    expect(tab).not.toContain('setCurrentSessionId(status.sessionId)')
  })
  it('retains the draft when the main process refuses history deletion', () => {
    const tab = readFileSync(join(__dirname, '../src/renderer/src/components/image/ImageTab.tsx'), 'utf8')
    const deletion = tab.slice(tab.indexOf('const handleDeleteSession'), tab.indexOf('const handleSettingsChange'))
    expect(deletion).toMatch(/if \(!result.success\)\s*\{[\s\S]*?return[\s\S]*?imageDrafts.remove\(sessionId\)/)
  })
})
